/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CreateApiKeyResponse extends SpeakeasyBase {
    /**
     * The ID of the API key.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The token of the API key.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "token" })
    token?: string;
}
